@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

olcnePipeline(
        branchPattern: new BranchPattern(master: 'oracle/release/1.25.5', feature: '(?!^oracle/release/$)(^.*$)'),
        customStages: [container: [enabled: false]],
	platforms: ['ol8', 'ol9', 'ol10'],
	architectures: ['x86_64', 'aarch64'],
	yumOL8Repos: ['ol8_appstream', 'ol8_codeready_builder'],
        ol8ModulesToDisable: ['go-toolset:ol8'],
        yumOL9Repos: ['ol9_appstream', 'ol9_codeready_builder'],
		yumOL10Repos: ['ol10_appstream', 'ol10_codeready_builder'],
)
